### ISSUE TITLE
Can you build w/o Git for Visual Studio 2013?

### ISSUE THREAD

**Issue by mavavilj** [mbrucher/AudioTK#1]
Trying to build for VS 2013 and CMake gives me the following CMake error when configuring:

Could NOT find Git (missing GIT_EXECUTABLE).

Is this some sort of online build?

**Comment by mbrucher** [comment]
I'm so used to having my own repository that I forgot this case...
OK, to make it work, you can comment the FIND(Git REQUIRED) line in the CMAkeLists.txt as well as the line with GIT_WC_INFO(${PROJECT_SOURCE_DIR} ATK)
I may end up removing this entirely, I wanted to use it for some versioning info, but never actually implemented it...

**Comment by mbrucher** [comment]
Should now be good on the develop branch.
