### ISSUE TITLE
cookiecutter template for ATK projects using DISTRHO plugin framework

### ISSUE THREAD

**Issue by SpotlightKid** [mbrucher/AudioTK#10]
This is not a bug or a feature request, just a headsup:

I have created a template for the (Python) tool [cookiecutter](https://github.com/audreyr/cookiecutter), which allows to set up an audio effect plugin project using ATK and the DISTRHO Plugin Framework ([DPF](https://github.com/DISTRHO/DPF) very quickly.

https://github.com/SpotlightKid/cookiecutter-dpf-audiotk

DPF helps to create audio plugins for multiple platforms (Linux, Windows, OS X) and multiple formats (LV2, VST, LADSPA, DSSI) from the same source. To create a new plugin project , you just get cookiecutter and then run:

```
cookiecutter https://github.com/SpotlightKid/cookiecutter-dpf-effect
```

The tool will then ask you about some information about your plugin, like the project, repository and plugin name, the author's name, email and domain, the plugin description, license and so forth.

A directory named after the value you gave for `repo_name` will be created and initialized as a git repository and DPF added as a git submodule.

Then just enter the directory and run make:

```
cd <repo_name>
make
```

The project template sets up the plugin source for a simple stereo delay effect. The `make` command compiles the plugin for all supported formats and places the binaries in the `bin` directory. 

You can change the implementation in the source (`plugins/<plugin_name>/Plugin<plugin_name>.cpp`) to your need.

_Share & Enjoy!_

**Comment by mbrucher** [comment]
That's great! Thanks!
