### ISSUE TITLE
python wrapper requirements

### ISSUE THREAD

**Issue by faroit** [mbrucher/AudioTK#12]
Hi, this is a great package

I wonder what are the requirements for python wrapper? Do you support python 2 and 3?

**Comment by mbrucher** [comment]
Hi,
Thanks!
The wrappers should be compatible with both versions, as the old examples were written with Python 2, and the more recent ones with Python 3. If there is an issue, just let me know, but a recent version of SWIG should make adequate wrappers for both versions.

**Comment by faroit** [comment]
cool, I've added you to [this list](https://github.com/faroit/awesome-python-scientific-audio)
