### ISSUE TITLE
Possible issue in ScalarNewtonRalphson.h ?

### ISSUE THREAD

**Issue by ptarabbia** [mbrucher/AudioTK#17]
Maybe I'm missing something, but:

optimize() does 
output[0] = optimize_impl(input, output);

and optimize_impl does (in some rare cases):
return output[-1]; 

if that last return happens on the very first call, doesn't the entire state get initialized with bad data ? Maybe there's something in place to prevent reading before the first value of the array, but I couldn't see it.

**Comment by mbrucher** [comment]
Actually no, there is no issue with this if and only if the filter has an output delay of 1. The last output sample is thus copied to the new output buffer.
When this is set, then output[i-1] is always defined for i inside [0;n[. Also this original output[-1] is also used as the value for the NR optimization.
