### ISSUE TITLE
CMake: Unable to find Boost header files (Boost 1.58)

### ISSUE THREAD

**Issue by mavavilj** [mbrucher/AudioTK#2]
I have Boost 1.58 installed.

Tried to add SET(BOOST_ROOT C:/Developer/Libs_cpp/boost_1_58_0/boost) to the CMakeLists.txt. Does not help.

Does the build not work with newer Boost versions?

**Comment by mbrucher** [comment]
Yes it works (it is the standard FindBoost from CMake). I tried it with different versions, works like a charm. Use the gui if there is an issue with setting up the variables: that's how I prefer to set Boost up if the path is not "standard".

**Comment by mavavilj** [comment]
Unable to find the requested Boost libraries.

Boost version: 1.58.0

Boost include path: C:/Developer/Libs_cpp/boost_1_58_0/boost

Could not find the following Boost libraries:

```
               boost_unit_test_framework
               boost_system
```

**Comment by mbrucher** [comment]
If you don't have a compiled version of Boost installed in BOOST_ROOT, it can't work. The libraries themselves are only required for the unit tests (be aware that the IO module is currently failing).

**Comment by mavavilj** [comment]
BOOST_ROOT points to a folder which is the same as this:
http://sourceforge.net/projects/boost/files/boost-binaries/1.58.0/

**Comment by mbrucher** [comment]
If you don't have the Boost libraries compiled for your compiler, it will not work.
You can also select the libraries by hand in the GUI if CMake doesn't pick them up automatically.

**Comment by mavavilj** [comment]
Got it working by compiling boost (like described here: http://choorucode.com/2014/06/06/how-to-build-boost-for-visual-studio-2013/), but the produced VS2013 project doesn't compile.

There are 86 errors about missing files regarding boost.

**Comment by mbrucher** [comment]
Good, we are moving forward! Strange that the package you got didn't contain everything.
The issue may be that you have the shared libraries, but for an obscure reason that I also observed before, CMake indicates to VS that it's the static version it needs.
If the error starts with something like "can't find boost-unit-framework*", then you need to recompile with static libraries (it's an option on b2). Otherwise, you need to give me the first errors to see what is going on.

**Comment by mavavilj** [comment]
So I switched to precompiled headers.
Here: http://sourceforge.net/projects/boost/files/boost-binaries/1.58.0/ and using the boost_1_58_0-msvc-12.0-32 one the project seems to compile (it runs for while), but it finally returns:

error LNK1181: cannot open input file 'ATKDelay.lib'
error LNK1181: cannot open input file 'ATKMock.lib'
error LNK1181: cannot open input file 'ATKDynamic.lib'
error LNK1181: cannot open input file 'ATKIO.lib'
error LNK1181: cannot open input file 'ATKMock.lib'
error LNK1181: cannot open input file 'ATSpecial.lib'

Both for static and shared compilation.

**Comment by mbrucher** [comment]
OK, that's a biggger issue.
First, the tests only work for shared libraries, but then it should find the new ATK libraries. Are you sure these are the first errors? If you try to compile only ATKMock, what happens?

**Comment by mavavilj** [comment]
compiling ATKMock_static builds, but ATKMock_test produces the error:
error LNK1181: cannot open input file 'ATKMock.lib'

Same is true for the other _test suffixed projects.

The above mentioned LNK1181s are the only errors produced.

**Comment by mbrucher** [comment]
As I've said, only the shared libraries can be linked with the unit tests. There should have been an error if you try to build tests without shared libraries, so something must be wrong when building the shared libraries.
What's the error when trying to build ATKMock?

**Comment by mavavilj** [comment]
So I mangled a bit with the CMake settings:
ENABLE_SHARED_LIBRARIES, ENABLE_STATIC_LIBRARIES, ENABLE_TESTS.

Crossing only ENABLE_STATIC_LIBRARIES and the whole project builds (Except for INSTALL and RUN_TESTS which are skipped), the other combinations fail (in varied ways).

Is this a usable build though? I can't seem to be able to build shared libraries at all.
Also this one does not produce a single .lib file anywhere.

**Comment by mbrucher** [comment]
Yes, the static build is the one I use for plugins actually (on Windows, you may need to change the run time libraries from /MD to /MT IIRC).
Still strange for the shared library build + tests, this is the one I use to develop and then use the static build for plugins. So you should get shared libraries available, except if there is an error during their build that you haven't shown me.
The .lib are scattered in the respective build folders. To have them all in one place, you need to install them. Standard CMake procedure.

**Comment by mavavilj** [comment]
ENABLE_SHARED_LIBRARIES and ENABLE_TESTS enabled:

Errors:

Error   268 error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(bool)" (__imp_??0predicate_result@test_tools@boost@@QAE@_N@Z) referenced in function "bool __cdecl boost::test_tools::tt_detail::check_frwd<struct boost::test_tools::check_is_small_t,double,double>(struct boost::test_tools::check_is_small_t,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,double const &,char const *,double const &,char const *)" (??$check_frwd@Ucheck_is_small_t@test_tools@boost@@NN@tt_detail@test_tools@boost@@YA_NUcheck_is_small_t@12@ABVlazy_ostream@unit_test@2@V?$basic_cstring@$$CBD@52@IW4tool_level@012@W4check_type@012@ABNPBD56@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   269 error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(bool)" (__imp_??0predicate_result@test_tools@boost@@QAE@_N@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   270 error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __thiscall boost::test_tools::predicate_result::operator!(void)const " (__imp_??7predicate_result@test_tools@boost@@QBE_NXZ) referenced in function "public: class boost::test_tools::predicate_result __thiscall boost::test_tools::close_at_tolerance<double>::operator()(double,double)const " (??R?$close_at_tolerance@N@test_tools@boost@@QBE?AVpredicate_result@12@NN@Z)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   271 error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __thiscall boost::test_tools::predicate_result::operator!(void)const " (__imp_??7predicate_result@test_tools@boost@@QBE_NXZ)  C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   272 error LNK2019: unresolved external symbol "__declspec(dllimport) public: class boost::basic_wrap_stringstream<char> & __thiscall boost::test_tools::predicate_result::message(void)" (__imp_?message@predicate_result@test_tools@boost@@QAEAAV?$basic_wrap_stringstream@D@3@XZ) referenced in function "public: class boost::test_tools::predicate_result __thiscall boost::test_tools::close_at_tolerance<double>::operator()(double,double)const " (??R?$close_at_tolerance@N@test_tools@boost@@QBE?AVpredicate_result@12@NN@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   273 error LNK2001: unresolved external symbol "__declspec(dllimport) public: class boost::basic_wrap_stringstream<char> & __thiscall boost::test_tools::predicate_result::message(void)" (__imp_?message@predicate_result@test_tools@boost@@QAEAAV?$basic_wrap_stringstream@D@3@XZ) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   274 error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::~predicate_result(void)" (__imp_??1predicate_result@test_tools@boost@@QAE@XZ) referenced in function "bool __cdecl boost::test_tools::tt_detail::check_frwd<struct boost::test_tools::check_is_close_t,double,double,struct boost::test_tools::percent_tolerance_t<double> >(struct boost::test_tools::check_is_close_t,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,double const &,char const *,double const &,char const *,struct boost::test_tools::percent_tolerance_t<double> const &,char const *)" (??$check_frwd@Ucheck_is_close_t@test_tools@boost@@NNU?$percent_tolerance_t@N@23@@tt_detail@test_tools@boost@@YA_NUcheck_is_close_t@12@ABVlazy_ostream@unit_test@2@V?$basic_cstring@$$CBD@52@IW4tool_level@012@W4check_type@012@ABNPBD56ABU?$percent_tolerance_t@N@12@6@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   275 error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::~predicate_result(void)" (__imp_??1predicate_result@test_tools@boost@@QAE@XZ)  C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   276 error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(class boost::test_tools::predicate_result const &)" (__imp_??0predicate_result@test_tools@boost@@QAE@ABV012@@Z) referenced in function "public: class boost::test_tools::predicate_result __thiscall boost::test_tools::close_at_tolerance<double>::operator()(double,double)const " (??R?$close_at_tolerance@N@test_tools@boost@@QBE?AVpredicate_result@12@NN@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   277 error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(class boost::test_tools::predicate_result const &)" (__imp_??0predicate_result@test_tools@boost@@QAE@ABV012@@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   278 error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::unit_test::unit_test_log_t & __cdecl boost::unit_test::singleton<class boost::unit_test::unit_test_log_t>::instance(void)" (__imp_?instance@?$singleton@Vunit_test_log_t@unit_test@boost@@@unit_test@boost@@SAAAVunit_test_log_t@23@XZ) referenced in function "void __cdecl boost::unit_test::`anonymous namespace'::`dynamic initializer for 'unit_test_log''(void)" (??__Eunit_test_log@?A0x2ab92bb9@unit_test@boost@@YAXXZ)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   279 error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class boost::unit_test::unit_test_log_t & __cdecl boost::unit_test::singleton<class boost::unit_test::unit_test_log_t>::instance(void)" (__imp_?instance@?$singleton@Vunit_test_log_t@unit_test@boost@@@unit_test@boost@@SAAAVunit_test_log_t@23@XZ)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   280 error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall boost::unit_test::unit_test_log_t::set_checkpoint(class boost::unit_test::basic_cstring<char const >,unsigned int,class boost::unit_test::basic_cstring<char const >)" (__imp_?set_checkpoint@unit_test_log_t@unit_test@boost@@QAEXV?$basic_cstring@$$CBD@23@I0@Z) referenced in function "protected: virtual void __thiscall ATK::FFTCheckerFilter<double>::process_impl(__int64)const " (?process_impl@?$FFTCheckerFilter@N@ATK@@MBEX_J@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   281 error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __thiscall boost::unit_test::unit_test_log_t::set_checkpoint(class boost::unit_test::basic_cstring<char const >,unsigned int,class boost::unit_test::basic_cstring<char const >)" (__imp_?set_checkpoint@unit_test_log_t@unit_test@boost@@QAEXV?$basic_cstring@$$CBD@23@I0@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   282 error LNK2019: unresolved external symbol "__declspec(dllimport) bool __cdecl boost::test_tools::tt_detail::check_impl(class boost::test_tools::predicate_result const &,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,unsigned int,...)" (__imp_?check_impl@tt_detail@test_tools@boost@@YA_NABVpredicate_result@23@ABVlazy_ostream@unit_test@3@V?$basic_cstring@$$CBD@63@IW4tool_level@123@W4check_type@123@IZZ) referenced in function "bool __cdecl boost::test_tools::tt_detail::check_frwd<struct boost::test_tools::check_is_close_t,double,double,struct boost::test_tools::percent_tolerance_t<double> >(struct boost::test_tools::check_is_close_t,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,double const &,char const *,double const &,char const *,struct boost::test_tools::percent_tolerance_t<double> const &,char const *)" (??$check_frwd@Ucheck_is_close_t@test_tools@boost@@NNU?$percent_tolerance_t@N@23@@tt_detail@test_tools@boost@@YA_NUcheck_is_close_t@12@ABVlazy_ostream@unit_test@2@V?$basic_cstring@$$CBD@52@IW4tool_level@012@W4check_type@012@ABNPBD56ABU?$percent_tolerance_t@N@12@6@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   283 error LNK2001: unresolved external symbol "__declspec(dllimport) bool __cdecl boost::test_tools::tt_detail::check_impl(class boost::test_tools::predicate_result const &,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,unsigned int,...)" (__imp_?check_impl@tt_detail@test_tools@boost@@YA_NABVpredicate_result@23@ABVlazy_ostream@unit_test@3@V?$basic_cstring@$$CBD@63@IW4tool_level@123@W4check_type@123@IZZ)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   284 error LNK1120: 8 unresolved externals   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\Debug\ATKMock.dll  ATKMock

ENABLE_SHARED_LIBRARIES enabled:

Errors:

Error   268 error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(bool)" (__imp_??0predicate_result@test_tools@boost@@QAE@_N@Z) referenced in function "bool __cdecl boost::test_tools::tt_detail::check_frwd<struct boost::test_tools::check_is_small_t,double,double>(struct boost::test_tools::check_is_small_t,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,double const &,char const *,double const &,char const *)" (??$check_frwd@Ucheck_is_small_t@test_tools@boost@@NN@tt_detail@test_tools@boost@@YA_NUcheck_is_small_t@12@ABVlazy_ostream@unit_test@2@V?$basic_cstring@$$CBD@52@IW4tool_level@012@W4check_type@012@ABNPBD56@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   269 error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(bool)" (__imp_??0predicate_result@test_tools@boost@@QAE@_N@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   270 error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __thiscall boost::test_tools::predicate_result::operator!(void)const " (__imp_??7predicate_result@test_tools@boost@@QBE_NXZ) referenced in function "public: class boost::test_tools::predicate_result __thiscall boost::test_tools::close_at_tolerance<double>::operator()(double,double)const " (??R?$close_at_tolerance@N@test_tools@boost@@QBE?AVpredicate_result@12@NN@Z)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   271 error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __thiscall boost::test_tools::predicate_result::operator!(void)const " (__imp_??7predicate_result@test_tools@boost@@QBE_NXZ)  C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   272 error LNK2019: unresolved external symbol "__declspec(dllimport) public: class boost::basic_wrap_stringstream<char> & __thiscall boost::test_tools::predicate_result::message(void)" (__imp_?message@predicate_result@test_tools@boost@@QAEAAV?$basic_wrap_stringstream@D@3@XZ) referenced in function "public: class boost::test_tools::predicate_result __thiscall boost::test_tools::close_at_tolerance<double>::operator()(double,double)const " (??R?$close_at_tolerance@N@test_tools@boost@@QBE?AVpredicate_result@12@NN@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   273 error LNK2001: unresolved external symbol "__declspec(dllimport) public: class boost::basic_wrap_stringstream<char> & __thiscall boost::test_tools::predicate_result::message(void)" (__imp_?message@predicate_result@test_tools@boost@@QAEAAV?$basic_wrap_stringstream@D@3@XZ) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   274 error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::~predicate_result(void)" (__imp_??1predicate_result@test_tools@boost@@QAE@XZ) referenced in function "bool __cdecl boost::test_tools::tt_detail::check_frwd<struct boost::test_tools::check_is_close_t,double,double,struct boost::test_tools::percent_tolerance_t<double> >(struct boost::test_tools::check_is_close_t,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,double const &,char const *,double const &,char const *,struct boost::test_tools::percent_tolerance_t<double> const &,char const *)" (??$check_frwd@Ucheck_is_close_t@test_tools@boost@@NNU?$percent_tolerance_t@N@23@@tt_detail@test_tools@boost@@YA_NUcheck_is_close_t@12@ABVlazy_ostream@unit_test@2@V?$basic_cstring@$$CBD@52@IW4tool_level@012@W4check_type@012@ABNPBD56ABU?$percent_tolerance_t@N@12@6@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   275 error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::~predicate_result(void)" (__imp_??1predicate_result@test_tools@boost@@QAE@XZ)  C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   276 error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(class boost::test_tools::predicate_result const &)" (__imp_??0predicate_result@test_tools@boost@@QAE@ABV012@@Z) referenced in function "public: class boost::test_tools::predicate_result __thiscall boost::test_tools::close_at_tolerance<double>::operator()(double,double)const " (??R?$close_at_tolerance@N@test_tools@boost@@QBE?AVpredicate_result@12@NN@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   277 error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall boost::test_tools::predicate_result::predicate_result(class boost::test_tools::predicate_result const &)" (__imp_??0predicate_result@test_tools@boost@@QAE@ABV012@@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   278 error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::unit_test::unit_test_log_t & __cdecl boost::unit_test::singleton<class boost::unit_test::unit_test_log_t>::instance(void)" (__imp_?instance@?$singleton@Vunit_test_log_t@unit_test@boost@@@unit_test@boost@@SAAAVunit_test_log_t@23@XZ) referenced in function "void __cdecl boost::unit_test::`anonymous namespace'::`dynamic initializer for 'unit_test_log''(void)" (??__Eunit_test_log@?A0x2ab92bb9@unit_test@boost@@YAXXZ)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   279 error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class boost::unit_test::unit_test_log_t & __cdecl boost::unit_test::singleton<class boost::unit_test::unit_test_log_t>::instance(void)" (__imp_?instance@?$singleton@Vunit_test_log_t@unit_test@boost@@@unit_test@boost@@SAAAVunit_test_log_t@23@XZ)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   280 error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall boost::unit_test::unit_test_log_t::set_checkpoint(class boost::unit_test::basic_cstring<char const >,unsigned int,class boost::unit_test::basic_cstring<char const >)" (__imp_?set_checkpoint@unit_test_log_t@unit_test@boost@@QAEXV?$basic_cstring@$$CBD@23@I0@Z) referenced in function "protected: virtual void __thiscall ATK::FFTCheckerFilter<double>::process_impl(__int64)const " (?process_impl@?$FFTCheckerFilter@N@ATK@@MBEX_J@Z)   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   281 error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __thiscall boost::unit_test::unit_test_log_t::set_checkpoint(class boost::unit_test::basic_cstring<char const >,unsigned int,class boost::unit_test::basic_cstring<char const >)" (__imp_?set_checkpoint@unit_test_log_t@unit_test@boost@@QAEXV?$basic_cstring@$$CBD@23@I0@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   282 error LNK2019: unresolved external symbol "__declspec(dllimport) bool __cdecl boost::test_tools::tt_detail::check_impl(class boost::test_tools::predicate_result const &,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,unsigned int,...)" (__imp_?check_impl@tt_detail@test_tools@boost@@YA_NABVpredicate_result@23@ABVlazy_ostream@unit_test@3@V?$basic_cstring@$$CBD@63@IW4tool_level@123@W4check_type@123@IZZ) referenced in function "bool __cdecl boost::test_tools::tt_detail::check_frwd<struct boost::test_tools::check_is_close_t,double,double,struct boost::test_tools::percent_tolerance_t<double> >(struct boost::test_tools::check_is_close_t,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,double const &,char const *,double const &,char const *,struct boost::test_tools::percent_tolerance_t<double> const &,char const *)" (??$check_frwd@Ucheck_is_close_t@test_tools@boost@@NNU?$percent_tolerance_t@N@23@@tt_detail@test_tools@boost@@YA_NUcheck_is_close_t@12@ABVlazy_ostream@unit_test@2@V?$basic_cstring@$$CBD@52@IW4tool_level@012@W4check_type@012@ABNPBD56ABU?$percent_tolerance_t@N@12@6@Z) C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\FFTCheckerFilter.obj   ATKMock
Error   283 error LNK2001: unresolved external symbol "__declspec(dllimport) bool __cdecl boost::test_tools::tt_detail::check_impl(class boost::test_tools::predicate_result const &,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned int,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,unsigned int,...)" (__imp_?check_impl@tt_detail@test_tools@boost@@YA_NABVpredicate_result@23@ABVlazy_ostream@unit_test@3@V?$basic_cstring@$$CBD@63@IW4tool_level@123@W4check_type@123@IZZ)    C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\TriangleCheckerFilter.obj  ATKMock
Error   284 error LNK1120: 8 unresolved externals   C:\Developer\Libs_cpp\AudioTK-develop\build\ATK\Mock\Debug\ATKMock.dll  ATKMock

---

Also I've never needed to done the CMake "install phase" since the CMakeLists.txt that I've seen in other libraries have had instructions for the installation as well, at least I guess. I don't know how to do the install.

**Comment by mbrucher** [comment]
Oh... I think I understand what is happening... ATKMock uses unit tests as well, I may need to check that tomorrow in depth... Meanwhile I pushed a fix that may be enough. The issue was because I changed Boost detection earlier this week and have not tested the behavior on Windows with a fresh 
CMake build.
