### ISSUE TITLE
error MSB3073 when trying to INSTALL (CMake, VS2013).

### ISSUE THREAD

**Issue by mavavilj** [mbrucher/AudioTK#3]
This is a continuation from: https://github.com/mbrucher/AudioTK/issues/2

Have downloaded latest develop branch. Generated with CMake for VS2013 using settings ENABLE_SHARED_LIBRARIES and ENABLE_TESTS.

After building (the ALL_BUILD project) I believe I need to build the INSTALL project in VS2013.

However this produces:

------- Rebuild All started: Project: INSTALL, Configuration: Release Win32 ------
  --Install configuration: "Release"
  CMake Error at ATK/cmake_install.cmake:39 (file):
    file cannot create directory: C:/Program Files (x86)/AudioTK/include/ATK.
    Maybe need administrative privileges.
  Call Stack (most recent call first):
    cmake_install.cmake:32 (include)

Followed by an error:

Error   1   error MSB3073: The command "setlocal "C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake if %errorlevel% neq 0 goto :cmEnd :cmEnd endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone :cmErrorLevel exit /b %1 :cmDone if %errorlevel% neq 0 goto :VCEnd :VCEnd" exited with code 1. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets  132 5   INSTALL

Running VS2013 with administrative privileges doesn't help.

**Comment by mbrucher** [comment]
Great, so I'll close #2 .
This may be because the install target will try to install the libraries in C:\Program Files\AudioTK. You may want to change the target to a location of your choice by changing CMAKE_INSTALL_PREFIX to a location you have permission for.

**Comment by mavavilj** [comment]
That fixed it.

But,

There were still two lines requesting git.h in the cmake_install.cmake file that need to be removed for non-git build.

And it installed to C:/Program Files (x86)/AudioTK even after pointing it to elsewhere.

It would also be nicer if it didn't produce 8 different .libs but one. Or can you use any of them separately from the others?

**Comment by mbrucher** [comment]
Done for git.h on the develop branch.
No, I don't want to have just one .lib, it's the point of the modular design. If you need just the core and the IO, you just need to link against the core and IO. Same if you only want the EQs, you don't need to ship the Dynamic or the Special (which has a dependency on FFTW by default, meaning that you have to check the licence). The only mandatory one is Core, and then some libraries do depend on Tools as well for the moment (I may split that one in 2 before 1.0.0 to make a difference between filter tools and utilities like the fast exp or FFT).

**Comment by mbrucher** [comment]
It will install to CMAKE_INSTALL_PREFIX when you regenerate the project. If you don't generate it, it doesn't apply the modifications (the gui doesn't save the changes to CMakeCache.txt except if you configure or generate).
