### ISSUE TITLE
Python chorus examples use non-existent filter class DoubleLowPassCoefficientsIIRFilter

### ISSUE THREAD

**Issue by SpotlightKid** [mbrucher/AudioTK#8]
The example scripts `Examples/delay/chorus.py` and `Examples/delay/display_chorus.py` want to import the `DoubleLowPassCoefficientsIIRFilter` from the `ATK.EQ` module. This module doesn't have a class of that name (anymore?).

I looked a the filter classes in `ATK/EQ.py`, but I wasn't clear to me what would be a suitable replacement class. I tried `DoubleRobertBristowJohnsonLowPassFilter` and the scripts seem to work with it, but I'm not sure whether the effect is comparable.

**Comment by mbrucher** [comment]
Indeed, I've renamed in 1.2.0 all the second order filters,a s they didn't have the "second order" qualifier in their name.
chorus and also the Python script that compared the low pass EQ should be fixed on the develop branch.
Thanks again for all the reports!

**Comment by SpotlightKid** [comment]
I can confirm that the Python errors are fixed.

However, running `Example/EQ/compare_ATK_LP.py` I get several of the following warnings:

```
swig/python detected a memory leak of type 'std::vector< double > *', no destructor found.
```

**Comment by mbrucher** [comment]
A swig template misplaced, should be fixed now!
